### ISSUE TITLE
"merge_bn.py", line 57, in merge_bn  nob.params[key][1].data[...] = bias

### ISSUE THREAD

**Issue by AbhimanyuAryan** [tolotrasamuel/real-time-object-detection-retraining-ncs-raspberry-pi#1]
https://tolotra.com/2018/09/15/how-to-retrain-ssd-mobilenet-for-real-time-object-detection-using-a-raspberry-pi-and-movidius-neural-compute-stick/

when running merge_bn.py

```
I0725 15:49:38.063462 17394 net.cpp:228] conv2/dw/bn does not need backward computation.
I0725 15:49:38.063469 17394 net.cpp:228] conv2/dw does not need backward computation.
I0725 15:49:38.063477 17394 net.cpp:228] conv1/relu does not need backward computation.
I0725 15:49:38.063484 17394 net.cpp:228] conv1/scale does not need backward computation.
I0725 15:49:38.063493 17394 net.cpp:228] conv1/bn does not need backward computation.
I0725 15:49:38.063499 17394 net.cpp:228] conv1 does not need backward computation.
I0725 15:49:38.063508 17394 net.cpp:228] conv1/dw/relu does not need backward computation.
I0725 15:49:38.063516 17394 net.cpp:228] conv1/dw/scale does not need backward computation.
I0725 15:49:38.063524 17394 net.cpp:228] conv1/dw/bn does not need backward computation.
I0725 15:49:38.063532 17394 net.cpp:228] conv1/dw does not need backward computation.
I0725 15:49:38.063539 17394 net.cpp:228] conv0/relu does not need backward computation.
I0725 15:49:38.063547 17394 net.cpp:228] conv0/scale does not need backward computation.
I0725 15:49:38.063555 17394 net.cpp:228] conv0/bn does not need backward computation.
I0725 15:49:38.063562 17394 net.cpp:228] conv0 does not need backward computation.
I0725 15:49:38.063575 17394 net.cpp:228] data_input_0_split does not need backward computation.
I0725 15:49:38.063583 17394 net.cpp:228] input does not need backward computation.
I0725 15:49:38.063591 17394 net.cpp:270] This network produces output detection_out
I0725 15:49:38.063716 17394 net.cpp:283] Network initialization done.
Traceback (most recent call last):
  File "merge_bn.py", line 63, in <module>
    merge_bn(net, net_deploy)
  File "merge_bn.py", line 57, in merge_bn
    nob.params[key][1].data[...] = bias
IndexError: Index out of range
```

**Comment by AbhimanyuAryan** [comment]
change needs to be done in example/MobileNetSSD_deploy.prototxt

I worked.....absolutely fine
